### ISSUE TITLE
key was 257 bytes (Expected 32) [RbNaCl::LengthError]

### ISSUE THREAD

**Issue by tomasell** [crypto-rb/rbnacl#179]
I cannot connect via SSH to some devices:
```
key was 257 bytes (Expected 32) [RbNaCl::LengthError]
--------------------------------------------------
/gems/rbnacl-4.0.2/lib/rbnacl/signatures/ed25519/verify_key.rb:33:in `initialize'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/ed25519.rb:25:in `new'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/ed25519.rb:25:in `initialize'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/ed25519.rb:128:in `new'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/ed25519.rb:128:in `initialize'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/ed25519.rb:152:in `new'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/ed25519.rb:152:in `read'
/gems/net-ssh-4.1.0/lib/net/ssh/key_factory.rb:113:in `block in classify_key'
/gems/net-ssh-4.1.0/lib/net/ssh/key_factory.rb:60:in `load_data_private_key'
/gems/net-ssh-4.1.0/lib/net/ssh/key_factory.rb:43:in `load_private_key'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/key_manager.rb:142:in `sign'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/methods/publickey.rb:62:in `authenticate_with'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/methods/publickey.rb:20:in `block in authenticate'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/key_manager.rb:122:in `block in each_identity'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/key_manager.rb:119:in `each'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/key_manager.rb:119:in `each_identity'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:80:in `block in authenticate'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:66:in `each'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:66:in `authenticate'
/gems/net-ssh-4.1.0/lib/net/ssh.rb:237:in `start'
```

I've to use net-ssh v4.1.0 (that requires rbnacl <5.0.0).

**Comment by tarcieri** [comment]
This is a Net::SSH bug. Ed25519 keys are 32-bytes.

It looks like it’s trying to pass a 2048-bit RSA key, in which case... wrong algorithm.
